- name: Installing php and apache on Ubuntu
  tags: apache-ubuntu
  apt:
    name:
       - apache2
       - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"
    
    #- name: Starting the servcie
    # tags: apache2service
    #servcie: 
    # name: apache2
    # state: started
    
