---
- hosts: linux:
  become: true
  become_method: sudo 
  tasks:


    - name: install apache and php package in ubuntu machine
      apt: 
       name:
         - apache2
         - libapache2-mod-php

       state: latest
       update_cache: yes
      when: ansible_distribution == "Ubuntu"


    - name: install httpd and php in Alma Linux
      yum:
        name:
          - httpd
          - php
        state: latest
        update_cache: yes
       when: ansible_distribution == "AlmaLinux"

    

    


    
          
